cd bios
./verify.sh bios_22.s
./verify.sh bios_22f_IV.s
./verify.sh bios_22sp.s
./verify.sh bios_22de.s
cd ..
cd rom
./verify.sh 81-149c.s
./verify.sh 81-232.s
cd ..
cd executables
./verify.sh cambio.s
./verify.sh cambio8.s
cd ..
